context:
  version: "0.64"

package:
  name: ktfmt
  version: ${{ version }}

source:
  url: https://github.com/facebook/ktfmt/archive/v${{ version }}.tar.gz
  sha256: e36494b88d8f42aad412573fbc834e3539e66aab40dba00e5e3433a6b04f0bfc

build:
  number: 0
  noarch: generic

requirements:
  host:
    - maven
    - openjdk =17
  run:
    - openjdk

tests:
  - script:
      - ktfmt --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A program that reformats Kotlin source code to comply with the common community standard for Kotlin code conventions.
  homepage: https://github.com/facebook/ktfmt
  repository: https://github.com/facebook/ktfmt

extra:
  recipe-maintainers:
    - danielnachun
