context:
  version: "0.63"

package:
  name: ktfmt
  version: ${{ version }}

source:
  url: https://github.com/facebook/ktfmt/archive/v${{ version }}.tar.gz
  sha256: 1f284160c50b3309d2a61ce22f9bd60aa7c8fc86d16aae0bac55ac132b242460

build:
  number: 0
  noarch: generic

requirements:
  host:
    - maven
    - openjdk =17
  run:
    - openjdk

tests:
  - script:
      - ktfmt --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A program that reformats Kotlin source code to comply with the common community standard for Kotlin code conventions.
  homepage: https://github.com/facebook/ktfmt
  repository: https://github.com/facebook/ktfmt

extra:
  recipe-maintainers:
    - danielnachun
