context:
  version: "0.60"

package:
  name: ktfmt
  version: ${{ version }}

source:
  url: https://github.com/facebook/ktfmt/archive/v${{ version }}.tar.gz
  sha256: b17647663bee46b528b8c80c38e241cb7c3d6fea896366dad408ecfed04bccc7

build:
  number: 0
  noarch: generic

requirements:
  host:
    - maven
    - openjdk =17
  run:
    - openjdk

tests:
  - script:
      - ktfmt --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A program that reformats Kotlin source code to comply with the common community standard for Kotlin code conventions.
  homepage: https://github.com/facebook/ktfmt
  repository: https://github.com/facebook/ktfmt

extra:
  recipe-maintainers:
    - danielnachun
